services:
  db:
    image: postgres:17.4
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - "6432:5432"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
